package com.acgass.springparkingapi.Domain;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "ParkingMeters")
public class ParkingMeter{

    private long id;
    private String location;
    private String timeRemaining;
    private String isOpen;
    private String moneyPaid;

    public ParkingMeter(){

    }

    public ParkingMeter(String location, long id, String timeRemaining) {
        this.id = id;
        this.location = location;
        this.timeRemaining = timeRemaining;
        this.isOpen = "true";
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public long getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "location")
    public String getLocation() {
        return location;
    }

    @DynamoDBAttribute(attributeName = "isOpen")
    public String getIsOpen() {
        return isOpen;
    }

    @DynamoDBAttribute(attributeName = "amountPaid")
    public String getMoneyPaid() {
        return moneyPaid;
    }

    @DynamoDBAttribute(attributeName = "timeRemaining")
    public String getTimeRemaining() {
        return timeRemaining;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setIsOpen(String open) {
        isOpen = open;
    }

    public void setMoneyPaid(String moneyPaid) {
        this.moneyPaid = moneyPaid;
    }

//    public String updateTime(String amountPaid){
//        // TODO: implement once util class is flushed out
//        return timeRemaining;
//    }

    public void setTimeRemaining(String timeRemaining) {
        this.timeRemaining = timeRemaining;
    }
}
